# Generated by Django 2.2.4 on 2020-03-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedata',
            name='updatedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
